spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:   dev		#开发环境
  application:
    name: microservicecloud-config-zj-dev
---
spring:
  profiles:   test		#测试环境
  application:
    name: microservicecloud-config-zj-test
# 保存格式为utf-8